name: build-check
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: ubuntu-setup
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get install clang-format
      - name: format-check
        run: |
          git log -n 5 --format="%h %B"
          git-clang-format --diff upstream/${{github.base_ref}}